version: '3.8'

services:
  web:
    build:
      context: ./main
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    
    volumes:
      - ./main/:/usr/src/app/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
    - mongodb
  
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
  
