version: '3.8'

services:
  web:
    build:
      context: ./main
      dockerfile: Dockerfile.prod
    command: gunicorn trading.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
    - mongodb
  
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db  
  
  
volumes:
  static_volume:
  media_volume:
  dbdata6: